server:
  port: 9087
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edu-online-messenger
    username: root
    password: root
  jpa:
    liquibase:
      enabled: true
      change-log: classpath:changelog-master.xml
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true